# IN-BUILD METHODS.

# emp_name=["aman","shivam"]
# # new_emp="kamal"

# # emp_name.append(new_emp)

# # print(emp_name)

# # for i in range(1,12):
# #     new_emp=input("Enter employe name :- ")
# #     emp_name.append(new_emp)
# # print("updated list :- ",emp_name)


# ----------extend------------

# emp_name=["aman","shivam"]
# new_emp="kamal"

# emp_name.append(new_emp)

# print(emp_name)

# for i in range(1,12):
#     new_emp=input("Enter employe name :- ")
#     emp_name.extend(new_emp)
# print("updated list :- ",emp_name)


# ---------------------pop()-------------------
# my_list=[100,200,300,400,500,600,700,800,900]

# my_list.pop()

# print(my_list)


# ---------remove()------------

# my_list=[100,200,300,400,500,600,700,800,900]

# my_list.remove(100)

# print(my_list)

# -------------------clear()------------------

# my_list=[100,200,300,400,500,600,700,800,900]

# my_list.clear()

# print(my_list)

# ----------------reverce()-----------------------
# my_list=[100,200,300,400,500,600,700,800,900]

# my_list.reverse()

# print(my_list)

# ---------------sort():- acending--------------- apply only homoginiash

# my_list=[100,200,300,400,500,600,700,800,900]

# my_list.sort()

# print(my_list)

# ------------sort(reverce=true) decending-------------

# my_list=[100,200,300,400,500,600,700,800,900]
# my_list.sort(reverse=True)
# print(my_list)


# -----------copy()---------------
# my_list=[100,200,300,400,500,600,700,800,900]

# d_l=my_list.copy()

# print(my_list)

# ---------inedex()----------------
# my_list=[100,200,300,400,500,600,700,800,900]

# my_list.index(100)

# print(my_list)

# -----------count()-----------

# my_list=[100,200,200,200,300,400,500,600,700,800,900]

# res=my_list.count(200)

# print(my_list)
# print(res)

# ------------unuversal------------------

# my_list=[100,200,300,400,500,600,700,800,900]
# print(sum(my_list))
# print(min(my_list))
# print(max(my_list))





















































